# Generated by Django 5.0.4 on 2024-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cloud_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='figma_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tg_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vk_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Сайт', 'Website'), ('Игра', 'Novell'), ('Мобильное приложение', 'Mobile App')], max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='course_number',
            field=models.CharField(choices=[('1 курс', 'First'), ('2 курс', 'Second'), ('3 курс', 'Third'), ('4 курс', 'Fourth')], max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(choices=[('2023-2024', 'First'), ('2022-2023', 'Second'), ('2021-2022', 'Third'), ('2020-2021', 'Fourth')], max_length=128),
        ),
    ]
