# Generated by Django 5.0.4 on 2024-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='ide',
            field=models.CharField(default='abcd', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='projectcoursenumber',
            name='ide',
            field=models.CharField(default='abcd', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='projectyear',
            name='ide',
            field=models.CharField(default='abcd', max_length=128, unique=True),
        ),
    ]
