# Generated by Django 5.0.4 on 2024-06-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_cloud_link_project_figma_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course_number',
            field=models.CharField(choices=[('1 курс', 'First Course'), ('2 курс', 'Second Course'), ('3 курс', 'Third Course'), ('4 курс', 'Fourth Course')], max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(choices=[('2023-2024', 'Year2023 2024'), ('2022-2023', 'Year2022 2023'), ('2021-2022', 'Year2021 2022'), ('2020-2021', 'Year2020 2021')], max_length=128),
        ),
    ]
