# Generated by Django 5.0.4 on 2024-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_course_number_alter_project_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Сайт', 'Сайт'), ('Игра', 'Игра'), ('Мобильное приложение', 'Мобильное Приложение')], max_length=128),
        ),
    ]
