# Generated by Django 5.0.4 on 2024-06-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course_number',
            field=models.CharField(choices=[('1 курс', 'Курс 1'), ('2 курс', 'Курс 2'), ('3 курс', 'Курс 3'), ('4 курс', 'Курс 4')], max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(choices=[('2023-2024', 'Год 2023 2024'), ('2022-2023', 'Год 2022 2023'), ('2021-2022', 'Год 2021 2022'), ('2020-2021', 'Год 2020 2021')], max_length=128),
        ),
    ]
