# Generated by Django 5.0.4 on 2024-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
