# Generated by Django 5.0.4 on 2024-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_photo1_project_photo2_project_photo3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='projects_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='projects_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='projects_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='projects_images'),
        ),
    ]
