# Generated by Django 5.0.4 on 2024-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_project_photo1_alter_project_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
